//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoluSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolu
    {
        public int id { get; set; }
        public int bolus_id { get; set; }
        public Nullable<int> animal_id { get; set; }
        public string AnimalInfo { get; set; }
    }
}
